name: Deploy synopsis prototype to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js site
        run: npm run build && npm run export

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out  # This must match your Next.js export output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1